- label: 'JIRA'
  message: '$issuePrefix'
  icon: 'jira'
  color: 'blue'
  url: 'https://u-hyu.atlassian.net/browse/$issuePrefix'
  when: '$issuePrefix'

- label: 'PR Size'
  message: 'Large'
  color: 'red'
  when: '$additions >= 500'

- label: 'PR Size'
  message: 'Medium'
  color: 'yellow'
  when: '$additions > 200 && $additions < 500'

- imageUrl: https://github.com/u-hyu/u-hyu/actions/workflows/ci.yml/badge.svg?branch=$branchName
  url: https://github.com/u-hyu/u-hyu/actions/workflows/ci.yml?query=branch:$branchName
