import type {
  TotalStats,
  BookmarkStat,
  FilteringStat,
  RecommendStat,
  MembershipStat,
  AdminBrandListResponse,
} from './types';

// 전체 통계 목 데이터
export const mockTotalStats: TotalStats = {
  totalBookmarkMyMap: 156,
  totalFiltering: 89,
  totalMembershipUsage: 234,
};

// 즐겨찾기 통계 목 데이터
export const mockBookmarkStats: BookmarkStat[] = [
  {
    categoryId: 2,
    categoryName: '영화/미디어',
    sumStatisticsBookmarksByCategory: 45,
    bookmarksByBrandList: [
      { brandName: 'CGV', sumBookmarksByBrand: 25 },
      { brandName: '메가박스', sumBookmarksByBrand: 15 },
      { brandName: '롯데시네마', sumBookmarksByBrand: 5 },
    ],
  },
  {
    categoryId: 3,
    categoryName: '워터파크/아쿠아리움',
    sumStatisticsBookmarksByCategory: 28,
    bookmarksByBrandList: [
      { brandName: '롯데월드 아쿠아리움', sumBookmarksByBrand: 18 },
      { brandName: '에버랜드', sumBookmarksByBrand: 10 },
    ],
  },
  {
    categoryId: 4,
    categoryName: '액티비티',
    sumStatisticsBookmarksByCategory: 32,
    bookmarksByBrandList: [
      { brandName: '클라이밍존', sumBookmarksByBrand: 20 },
      { brandName: '서핑존', sumBookmarksByBrand: 12 },
    ],
  },
  {
    categoryId: 5,
    categoryName: '뷰티(피부과, 클리닉)',
    sumStatisticsBookmarksByCategory: 39,
    bookmarksByBrandList: [
      { brandName: '아름다운 피부과', sumBookmarksByBrand: 25 },
      { brandName: '청담동 클리닉', sumBookmarksByBrand: 14 },
    ],
  },
];

// 필터링 통계 목 데이터
export const mockFilteringStats: FilteringStat[] = [
  {
    categoryId: 6,
    categoryName: '건강(제약, 영양제 등)',
    sumStatisticsFilterByCategory: 18,
  },
  {
    categoryId: 7,
    categoryName: '생활/편의',
    sumStatisticsFilterByCategory: 42,
  },
  {
    categoryId: 8,
    categoryName: '쇼핑',
    sumStatisticsFilterByCategory: 35,
  },
  {
    categoryId: 9,
    categoryName: '음식점',
    sumStatisticsFilterByCategory: 58,
  },
  {
    categoryId: 10,
    categoryName: '베이커리/디저트',
    sumStatisticsFilterByCategory: 25,
  },
];

// 추천 통계 목 데이터
export const mockRecommendStats: RecommendStat[] = [
  {
    categoryId: 6,
    categoryName: '건강(제약, 영양제 등)',
    sumStatisticsRecommendationByCategory: 18,
    recommendationsByBrandList: [
      { brandName: '건강약국', sumRecommendationsByBrand: 12 },
      { brandName: '영양제샵', sumRecommendationsByBrand: 6 },
    ],
  },
  {
    categoryId: 7,
    categoryName: '생활/편의',
    sumStatisticsRecommendationByCategory: 42,
    recommendationsByBrandList: [
      { brandName: 'GS25', sumRecommendationsByBrand: 25 },
      { brandName: 'CU', sumRecommendationsByBrand: 17 },
    ],
  },
  {
    categoryId: 8,
    categoryName: '쇼핑',
    sumStatisticsRecommendationByCategory: 35,
    recommendationsByBrandList: [
      { brandName: '올리브영', sumRecommendationsByBrand: 20 },
      { brandName: '다이소', sumRecommendationsByBrand: 15 },
    ],
  },
  {
    categoryId: 9,
    categoryName: '음식점',
    sumStatisticsRecommendationByCategory: 58,
    recommendationsByBrandList: [
      { brandName: '맥도날드', sumRecommendationsByBrand: 30 },
      { brandName: '버거킹', sumRecommendationsByBrand: 18 },
      { brandName: 'KFC', sumRecommendationsByBrand: 10 },
    ],
  },
  {
    categoryId: 10,
    categoryName: '베이커리/디저트',
    sumStatisticsRecommendationByCategory: 25,
    recommendationsByBrandList: [
      { brandName: '파리크라상', sumRecommendationsByBrand: 15 },
      { brandName: '파리바게트', sumRecommendationsByBrand: 10 },
    ],
  },
];

// 멤버십 통계 목 데이터
export const mockMembershipStats: MembershipStat[] = [
  {
    categoryId: 11,
    categoryName: '테마파크',
    sumStatisticsMembershipUsageByCategory: 67,
    membershipUsageByBrandList: [
      { brandName: '롯데월드', sumMembershipUsageByBrand: 40 },
      { brandName: '에버랜드', sumMembershipUsageByBrand: 27 },
    ],
  },
  {
    categoryId: 12,
    categoryName: '공연/전시',
    sumStatisticsMembershipUsageByCategory: 23,
    membershipUsageByBrandList: [
      { brandName: '예술의전당', sumMembershipUsageByBrand: 15 },
      { brandName: '세종문화회관', sumMembershipUsageByBrand: 8 },
    ],
  },
  {
    categoryId: 14,
    categoryName: '여행/교통',
    sumStatisticsMembershipUsageByCategory: 44,
    membershipUsageByBrandList: [
      { brandName: '카카오T', sumMembershipUsageByBrand: 28 },
      { brandName: '우버', sumMembershipUsageByBrand: 16 },
    ],
  },
];

// 브랜드 목록 목 데이터
export const mockAdminBrandListResponse: AdminBrandListResponse = {
  brandList: [
    {
      brandId: 1,
      brandName: '파리크라상',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%91%E1%85%A1%E1%84%85%E1%85%B5%E1%84%8F%E1%85%B3%E1%84%85%E1%85%A1%E1%84%89%E1%85%A1%E1%86%BC.png',
      data: [
        { grade: 'VIP', description: '1천원당 100원 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '1천원당 50원 할인', benefitType: 'DISCOUNT' },
        { grade: 'VVIP', description: '1천원당 100원 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 10,
      usageLimit: '일 1회 [VVIP/VIP] 일 최대 2만원까지 할인 가능 월 최대 10만원까지 할인 가능 [우수] 일 최대 1만원까지 할인 가능 월 최대 10만원까지 할인 가능',
      usageMethod: '결제 시 직원에게 멤버십 카드 제시  *꼭 확인하세요 - 중복 할인 불가 - 일부매장(올림픽공원점, 잠실점, 서초래미안점,이대서울병원점, 서울대병원점, 서울역, 서울역SW, 연세세브란스, 예술의전당, 여의도 현대백화점)에서는 해당 혜택적용 불가 - 결제금액의 0.1% 해피포인트로 적립 가능  대표문의 파리크라상 031-740-5500',
      storeType: 'OFFLINE',
    },
    {
      brandId: 2,
      brandName: 'CGV',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/CGV.png',
      data: [
        { grade: 'GOOD', description: '2D영화 2천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '2D영화 2천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'VVIP', description: '2D영화 2천원 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 2,
      usageLimit: '월 1회(※쿠폰 소진 시 발급이 불가 할 수 있습니다.)',
      usageMethod: '* 쿠폰 다운로드 방법\nU+ 멤버십앱 메인 화면 우측 상단 검색(돋보기 모양) 클릭 > CGV 검색 > 제휴사 클릭 후 \'다운로드\' 클릭 > U+멤버십 앱 메인 화면 우측 상단 \'마이\' 클릭 > 내 쿠폰함 > 쿠폰 내 이용방법 및 유의사항 참고\n\n* 쿠폰등록 방법\nCGV 웹/앱 : 로그인 > 마이cgv > 쿠폰함 > 쿠폰등록\nPOS/키오스크 > 영화/좌석 선택 > 결제 > 할인받고 결제할래요 > CGV 할인쿠폰 > 쿠폰 바코드 리딩 OR 쿠폰번호 수기입력 > 잔여금액 결제\n\n*꼭 확인하세요\n- 본 쿠폰은 CGV 일반관에서 상영하는 2D일반영화 예매시 사용가능\n- 아래 표기된 가격체계가 상이한 영화 및 일부지점에서는 차액지불 여부와 관계 없이 사용불가\n(CINE de CHEF, GOLD CLASS, SWEET BOX 등 CGV 특별관 및 특별좌석)\n- 타 제휴할인 및 쿠폰적용은 중복사용 불가',
      storeType: 'OFFLINE',
    },
    {
      brandId: 3,
      brandName: '지니뮤직',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%8C%E1%85%B5%E1%84%82%E1%85%B5%E1%84%86%E1%85%B2%E1%84%8C%E1%85%B5%E1%86%A8.png',
      data: [
        { grade: 'VVIP', description: '유독 Pick2 23% 할인 혜택\\① 지니뮤직 앱 음악감상 ② 메가커피 HOT 아메리카노 월 2잔', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '유독 Pick2 23% 할인 혜택\\① 지니뮤직 앱 음악감상 ② 메가커피 HOT 아메리카노 월 2잔', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '유독 Pick2 23% 할인 혜택\\① 지니뮤직 앱 음악감상 ② 메가커피 HOT 아메리카노 월 2잔', benefitType: 'DISCOUNT' },
      ],
      categoryId: 1,
      usageLimit: '월 1회',
      usageMethod: '- 아래 [혜택보기]를 통해 \'유독 Pick2 지니뮤직+메가커피\' 구독 - 지니뮤직 : 지니뮤직 앱 설치 후 지니뮤직 앱에서 음악감상 - 메가커피 : 유독 > MY쿠폰에서 쿠폰 발급 후 결제 시 쿠폰 사용   * 꼭 확인하세요 - 가입 시 혜택을 받으실 수 있습니다. - 유독 Pick2를 구성하는 혜택이 하나라도 사용되었다면 구독을 철회할 수 없으며 부분환불을 제공하지 않습니다.   대표문의 U+ 114 (무료) / 1544-0010 (유료)',
      storeType: 'ONLINE',
    },
    {
      brandId: 4,
      brandName: '뽀로로파크',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%88%E1%85%A9%E1%84%85%E1%85%A9%E1%84%85%E1%85%A9%E1%84%91%E1%85%A1%E1%84%8F%E1%85%B3.png',
      data: [
        { grade: 'VVIP', description: '뽀로로파크 입장권 본인 40% 할인+동반 1인 30% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '뽀로로파크 입장권 본인 40% 할인+동반 1인 30% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '뽀로로파크 입장권 본인 40% 할인+동반 1인 30% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '월 1회',
      usageMethod: '■ 쿠폰 다운로드 방법 U+ 멤버십앱 메인 화면 우측 상단 검색(돋보기 모양)클릭 &gt; 뽀로로파크 검색 &gt; 제휴사 클릭 후 &#39;다운로드&#39; 클릭 &gt; &nbsp;U+멤버십 앱 메인 화면 우측 상단 &#39;마이&#39; 클릭 &gt; 내 쿠폰함 &gt; 쿠폰 내 이용방법 및 유의사항 참고&nbsp;  ■ &nbsp;쿠폰 사용 방법 - STEP 1. 멤버십 앱 내 쿠폰 다운로드 - STEP 2. 내 쿠폰함에서 다운로드한 쿠폰 확인 - STEP 3. 결제 전 매장 직원에게 쿠폰 제시  ■ &nbsp;꼭 확인하세요 [본인 및 동반인 기준] - 본인 : 대인(14세 이상) - 동반인 : 소인(12개월 이상 ~ 13세), 대인(14세 이상)  [유의사항] U+멤버십 앱에 있는 쿠폰만 사용하실 수 있습니다.(캡처한 쿠폰 이미지 사용할 수 없음) 이 쿠폰은 현장 결제 시에만 사용하실 수 있습니다.(온라인 구매 시 할인 적용 안 됨) 쿠폰은 다운로드한 달의 마지막 날까지 사용하실 수 있습니다. 다른 쿠폰/포인트와 중복으로 사용하실 수 없습니다. 다른 할인 행사/제휴 카드 혜택과 중복으로 적용되지 않습니다. 일부 매장에서는 혜택을 이용하실 수 없습니다. 아래 혜택 적용 매장을 확인하고 이용해 주시기 바랍니다.  [혜택 적용 매장(&rsquo;25년 6월 1일 기준)] * 인천광역시: 뽀로로테마파크 월미도점 * 서울특별시: 뽀로로파크 금천점, 뽀로로파크 영등포점 * 경기도: 프리미어 뽀로로테마파크 다산 위드 트래블, 뽀로로파크 일산킨텍스점  ■ 대표문의 TEL : 031-698-2000 HOME : http://www.pororopark.com/',
      storeType: 'OFFLINE',
    },
    {
      brandId: 5,
      brandName: '아르떼 키즈파크 제주',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%8B%E1%85%A1%E1%84%85%E1%85%B3%E1%84%84%E1%85%A6%20%E1%84%8F%E1%85%B5%E1%84%8C%E1%85%B3%E1%84%91%E1%85%A1%E1%84%8F%E1%85%B3%20%E1%84%8C%E1%85%A6%E1%84%8C%E1%85%AE.png',
      data: [
        { grade: 'VVIP', description: '이용권 최대 20% 할인(본인 포함 최대 4인까지)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '이용권 최대 20% 할인(본인 포함 최대 4인까지)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '이용권 최대 20% 할인(본인 포함 최대 4인까지)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '제한없음',
      usageMethod: '■ 쿠폰 사용 방법 - 결제 시 현장에서 LG U+ 멤버십 카드 제시  ■ 혜택 적용점 및 혜택 기준 - 아르떼 키즈파크 제주점&nbsp; - 이용권 20% 할인(동반 3인까지)  ■ 유의 사항 - 선착순 쿠폰 소진, 전산 에러 등으로 인해 쿠폰 발급 불가 시 대체 혜택을 받으실 수 없습니다. - 당사 또는 제휴사 사정으로 인해 혜택이 조기 종료될 수 있습니다. - 해당 쿠폰은 제휴 기간인 2025.07.01 ~ 2025.12.31까지 사용 가능합니다. - 본 쿠폰은 아르떼 키즈파크 제주에서 본인 포함 최대 4인까지 사용 가능합니다. - 제주도민, 국가유공자 등 할인대상자 중복 사용 불가합니다  ■ 대표 문의 TEL: 제주 064-799-7007&nbsp; HOME: https://www.artekidspark.com',
      storeType: 'OFFLINE',
    },
    {
      brandId: 6,
      brandName: '원더빌리지',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%8B%E1%85%AF%E1%86%AB%E1%84%83%E1%85%A5%E1%84%87%E1%85%B5%E1%86%AF%E1%84%85%E1%85%B5%E1%84%8C%E1%85%B5.png',
      data: [
        { grade: 'GOOD', description: '원더빌리지 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
        { grade: 'VVIP', description: '원더빌리지 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '원더빌리지 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '월 1회',
      usageMethod: '■ 쿠폰 다운로드 방법 U+ 멤버십앱 메인 화면 우측 상단 검색(돋보기 모양)클릭 &gt; 원더빌리지 검색 &gt; 제휴사 클릭 후 &#39;다운로드&#39; 클릭 &gt; &nbsp;U+멤버십 앱 메인 화면 우측 상단 &#39;마이&#39; 클릭 &gt; 내 쿠폰함 &gt; 쿠폰 내 이용방법 및 유의사항 참고&nbsp;  ■ &nbsp;쿠폰 사용 방법 - STEP 1. 멤버십 앱 내 쿠폰 다운로드 - STEP 2. 내 쿠폰함에서 다운로드한 쿠폰 확인 - STEP 3. 결제 전 매장 직원에게 쿠폰 제시  ■ &nbsp;꼭 확인하세요&nbsp; &nbsp;- 이 쿠폰은 원더빌리지 고양점에서 사용하실 수 있습니다. &nbsp;- 이 쿠폰은 다운로드한 달의 마지막 날까지 사용하실 수 있습니다. &nbsp;- 이 쿠폰은 본인 포함 최대 4명까지 혜택을 이용하실 수 있습니다. &nbsp;- 이 쿠폰은 현장 결제 시에만 사용 가능하며, 다른 할인 혜택과 중복으로 이용하실 수 없습니다. &nbsp;- 방문 전 원더빌리지 홈페이지의 이용 안내와 운영 정책을 꼭 읽어 주시기 바랍니다 &nbsp;- 캡처한 쿠폰 이미지는 사용하실 수 없습니다. &nbsp;- 기간이 지난 쿠폰은 사용하거나 다시 발급받으실 수 없습니다. &nbsp;- 쿠폰 사용 기간은 연장할 수 없습니다. &nbsp;- U+ 멤버십 포인트와 함께 사용하실 수 없습니다. &nbsp;- 환불과 관련된 사항은 원더래빗의 규정을 따릅니다. &nbsp;- 이 쿠폰은 상품권이나 현금으로 교환하실 수 없습니다. &nbsp;- 이 쿠폰은 다른 쿠폰[종이 상품권, 모바일 상품권(금액권/제품권), 할인 쿠폰, 기타 쿠폰]과 중복으로 사용하실 수 없습니다.&nbsp;  ■ 문의&nbsp; &nbsp;- 031-5173-3457 (오전 10시~오후 6시)',
      storeType: 'OFFLINE',
    },
    {
      brandId: 7,
      brandName: '원더파크',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%8B%E1%85%AF%E1%86%AB%E1%84%83%E1%85%A5%E1%84%91%E1%85%A1%E1%84%8F%E1%85%B3.png',
      data: [
        { grade: 'VIP', description: '원더파크 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
        { grade: 'VVIP', description: '원더파크 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '원더파크 입장권 25% 할인 (최대 4인)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '월 1회',
      usageMethod: '■ 쿠폰 다운로드 방법 U+ 멤버십앱 메인 화면 우측 상단 검색(돋보기 모양)클릭 &gt; 원더파크 검색 &gt; 제휴사 클릭 후 &#39;다운로드&#39; 클릭 &gt; &nbsp;U+멤버십 앱 메인 화면 우측 상단 &#39;마이&#39; 클릭 &gt; 내 쿠폰함 &gt; 쿠폰 내 이용방법 및 유의사항 참고&nbsp;  ■ 쿠폰 사용 방법 - STEP 1. 멤버십 앱 내 쿠폰 다운로드 - STEP 2. 내 쿠폰함에서 다운로드한 쿠폰 확인 - STEP 3. 결제 전 1층 안내데스크 직원에게 쿠폰 제시&nbsp;  ■ 나이 기준 - 대인 : 중학생 이상 - 소인 : 36개월~초등학생 - 영유아 : 36개월 미만(증빙 서류 지참 시 무료 입장)나이 기준  ■ &nbsp;꼭 확인하세요&nbsp; - 이 쿠폰은 원더파크 현장 매표소에서만 사용 가능합니다. - 이 쿠폰은 고객님 본인 명의의 U+멤버십 카드당 매달 1장 다운로드 가능합니다. - 이 쿠폰은 고객님 본인 포함 최대 4인까지 혜택을 이용하실 수 있습니다. - 일일 입장 제한 인원과 관계없이 입장하실 수 있습니다. - 캡처한 쿠폰 이미지는 사용하실 수 없습니다. - 이 쿠폰은 다운로드한 달의 마지막 날까지 사용 가능합니다. - 기간이 지난 쿠폰은 재발급 불가하며, 기한 연장이 불가합니다. - U+ 멤버십 포인트와 함께 사용 불가합니다. - 이 쿠폰은 다른 사람에게 넘겨주거나 판매하실 수 없습니다. - 이 혜택을 이용하면 포인트를 적립하거나 제휴할인 카드 혜택을 받으실 수 없습니다. - 이 쿠폰은 다른 제휴 이벤트/ 쿠폰/ 할인혜택과 중복으로 적용 불가합니다. - 환불과 관련된 사항은 원더파크의 규정을 따릅니다.  ■ 문의&nbsp; 원더파크 고객센터(1555-5443, 평일 오전 10시~오후 6시, 유료) *3/6/9/12월 첫째주 월요일은 정기 휴관일로 고객센터를 운영하지 않습니다.',
      storeType: 'OFFLINE',
    },
    {
      brandId: 8,
      brandName: '서울랜드',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%89%E1%85%A5%E1%84%8B%E1%85%AE%E1%86%AF%E1%84%85%E1%85%A2%E1%86%AB%E1%84%83%E1%85%B3.png',
      data: [
        { grade: 'VVIP', description: '종합이용권 50% 할인(동반 1인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '종합이용권 50% 할인(동반 1인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '종합이용권 40% 할인(동반 1인 30% 할인)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '일 1회',
      usageMethod: '결제 시 직원에게 멤버십 카드 제시  *꼭 확인하세요 - 중복할인 불가  대표문의 서울랜드 02-509-6000',
      storeType: 'OFFLINE',
    },
    {
      brandId: 9,
      brandName: '뽀로로아쿠아빌리지',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%88%E1%85%A9%E1%84%85%E1%85%A9%E1%84%85%E1%85%A9%E1%84%8B%E1%85%A1%E1%84%8F%E1%85%AE%E1%84%8B%E1%85%A1%E1%84%87%E1%85%B5%E1%86%AF%E1%84%85%E1%85%B5%E1%84%8C%E1%85%B5.jpg',
      data: [
        { grade: 'VIP', description: '입장권 35% 할인(본인 포함 3인)', benefitType: 'DISCOUNT' },
        { grade: 'VVIP', description: '입장권 35% 할인(본인 포함 3인)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '입장권 35% 할인(본인 포함 3인)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '일 1회',
      usageMethod: '결제 시 직원에게 멤버십 카드 제시   *꼭 확인하세요 - 모든 할인은 정상가 기준에서 할인 혜택이 제공 됩니다. - 타 제휴 및 이벤트할인과 중복 할인 불가합니다. - 이용시간 및 상세 이용안내는 뽀로로아쿠아빌리지 홈페이지 참고 바랍니다.  대표문의 뽀로로아쿠아빌리지 1588-2299  ※정기 보수 공사로 인한 휴장안내 휴장 일시 : 2023. 03. 11(월)~ 2023. 03. 22(금) 3월 23일(토)부터 개장',
      storeType: 'OFFLINE',
    },
    {
      brandId: 10,
      brandName: '롯데월드 아이스링크',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/%E1%84%85%E1%85%A9%E1%86%BA%E1%84%83%E1%85%A6%E1%84%8B%E1%85%AF%E1%86%AF%E1%84%83%E1%85%B3%20%E1%84%8B%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%89%E1%85%B3%E1%84%85%E1%85%B5%E1%86%BC%E1%84%8F%E1%85%B3.png',
      data: [
        { grade: 'VVIP', description: '입장권 50% 할인 (동반 1인 포함)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '입장권 50% 할인 (동반 1인 포함)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '입장권 50% 할인 (동반 1인 포함)', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '일 1회',
      usageMethod: '결제 시 직원에게 멤버십 카드 제시  *꼭 확인하세요 - 아이스링크 야간제외  - 중복할인 불가   대표문의 롯데월드 1661-2000',
      storeType: 'OFFLINE',
    },
    {
      brandId: 11,
      brandName: '스타벅스',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/starbucks.png',
      data: [
        { grade: 'VVIP', description: '아메리카노 1잔 무료', benefitType: 'GIFT' },
        { grade: 'VIP', description: '아메리카노 1잔 무료', benefitType: 'GIFT' },
        { grade: 'GOOD', description: '아메리카노 1잔 무료', benefitType: 'GIFT' },
      ],
      categoryId: 3,
      usageLimit: '월 1회',
      usageMethod: '멤버십 앱에서 쿠폰 다운로드 후 현장에서 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 12,
      brandName: '올리브영',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/oliveyoung.png',
      data: [
        { grade: 'VVIP', description: '전 상품 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 8,
      usageLimit: '월 2회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 13,
      brandName: '네이버',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/naver.png',
      data: [
        { grade: 'VVIP', description: '네이버페이 포인트 2배 적립', benefitType: 'POINT' },
        { grade: 'VIP', description: '네이버페이 포인트 1.5배 적립', benefitType: 'POINT' },
        { grade: 'GOOD', description: '네이버페이 포인트 1배 적립', benefitType: 'POINT' },
      ],
      categoryId: 1,
      usageLimit: '제한없음',
      usageMethod: '네이버페이 결제 시 자동 적용',
      storeType: 'ONLINE',
    },
    {
      brandId: 14,
      brandName: '쿠팡',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/coupang.png',
      data: [
        { grade: 'VVIP', description: '무료배송 + 5% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '무료배송 + 3% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '무료배송', benefitType: 'GIFT' },
      ],
      categoryId: 8,
      usageLimit: '제한없음',
      usageMethod: '쿠팡 앱에서 자동 적용',
      storeType: 'ONLINE',
    },
    {
      brandId: 15,
      brandName: '배달의민족',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/baemin.png',
      data: [
        { grade: 'VVIP', description: '배달팁 무료 + 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '배달팁 무료 + 5% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '배달팁 무료', benefitType: 'GIFT' },
      ],
      categoryId: 9,
      usageLimit: '월 5회',
      usageMethod: '배달의민족 앱에서 자동 적용',
      storeType: 'ONLINE',
    },
    {
      brandId: 16,
      brandName: '토스',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/toss.png',
      data: [
        { grade: 'VVIP', description: '토스캐시백 3%', benefitType: 'POINT' },
        { grade: 'VIP', description: '토스캐시백 2%', benefitType: 'POINT' },
        { grade: 'GOOD', description: '토스캐시백 1%', benefitType: 'POINT' },
      ],
      categoryId: 1,
      usageLimit: '제한없음',
      usageMethod: '토스 앱에서 자동 적용',
      storeType: 'ONLINE',
    },
    {
      brandId: 17,
      brandName: '메가박스',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/megabox.png',
      data: [
        { grade: 'VVIP', description: '2D영화 3천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '2D영화 2천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '2D영화 1천원 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 2,
      usageLimit: '월 2회',
      usageMethod: '메가박스 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 18,
      brandName: '롯데시네마',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/lottecinema.png',
      data: [
        { grade: 'VVIP', description: '2D영화 3천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '2D영화 2천원 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '2D영화 1천원 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 2,
      usageLimit: '월 2회',
      usageMethod: '롯데시네마 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 19,
      brandName: 'GS25',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/gs25.png',
      data: [
        { grade: 'VVIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 7% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 7,
      usageLimit: '일 1회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 20,
      brandName: 'CU',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/cu.png',
      data: [
        { grade: 'VVIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 7% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 7,
      usageLimit: '일 1회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 21,
      brandName: '세븐일레븐',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/seveneleven.png',
      data: [
        { grade: 'VVIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 7% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 7,
      usageLimit: '일 1회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 22,
      brandName: '맥도날드',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/mcdonalds.png',
      data: [
        { grade: 'VVIP', description: '전 메뉴 20% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 메뉴 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 메뉴 10% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 9,
      usageLimit: '일 2회',
      usageMethod: '맥도날드 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 23,
      brandName: '버거킹',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/burgerking.png',
      data: [
        { grade: 'VVIP', description: '전 메뉴 20% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 메뉴 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 메뉴 10% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 9,
      usageLimit: '일 2회',
      usageMethod: '버거킹 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 24,
      brandName: 'KFC',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/kfc.png',
      data: [
        { grade: 'VVIP', description: '전 메뉴 20% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 메뉴 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 메뉴 10% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 9,
      usageLimit: '일 2회',
      usageMethod: 'KFC 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 25,
      brandName: '파리바게트',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/parisbaguette.png',
      data: [
        { grade: 'VVIP', description: '전 상품 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 10,
      usageLimit: '일 1회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 26,
      brandName: '던킨도너츠',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/dunkin.png',
      data: [
        { grade: 'VVIP', description: '전 상품 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '전 상품 10% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '전 상품 5% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 10,
      usageLimit: '일 1회',
      usageMethod: '결제 시 멤버십 카드 제시',
      storeType: 'OFFLINE',
    },
    {
      brandId: 27,
      brandName: '롯데월드',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/lotteworld.png',
      data: [
        { grade: 'VVIP', description: '종합이용권 50% 할인(동반 2인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '종합이용권 40% 할인(동반 1인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '종합이용권 30% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '월 1회',
      usageMethod: '롯데월드 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 28,
      brandName: '에버랜드',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/everland.png',
      data: [
        { grade: 'VVIP', description: '종합이용권 50% 할인(동반 2인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '종합이용권 40% 할인(동반 1인 30% 할인)', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '종합이용권 30% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 11,
      usageLimit: '월 1회',
      usageMethod: '에버랜드 앱에서 쿠폰 다운로드 후 사용',
      storeType: 'OFFLINE',
    },
    {
      brandId: 29,
      brandName: '카카오T',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/kakaoT.png',
      data: [
        { grade: 'VVIP', description: '택시 요금 20% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '택시 요금 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '택시 요금 10% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 14,
      usageLimit: '월 10회',
      usageMethod: '카카오T 앱에서 자동 적용',
      storeType: 'ONLINE',
    },
    {
      brandId: 30,
      brandName: '우버',
      brandImg: 'https://uhyu-bucket.s3.ap-northeast-2.amazonaws.com/logo/uber.png',
      data: [
        { grade: 'VVIP', description: '우버 요금 20% 할인', benefitType: 'DISCOUNT' },
        { grade: 'VIP', description: '우버 요금 15% 할인', benefitType: 'DISCOUNT' },
        { grade: 'GOOD', description: '우버 요금 10% 할인', benefitType: 'DISCOUNT' },
      ],
      categoryId: 14,
      usageLimit: '월 10회',
      usageMethod: '우버 앱에서 자동 적용',
      storeType: 'ONLINE',
    },
  ],
  hasNext: false,
  totalPages: 0,
  currentPage: 0,
};
