import type { Brand } from '../types';

export const BRANDS: Brand[] = [
  {
    id: 'cgv',
    name: 'CGV',
    color: '#E53E3E',
    bgColor: 'bg-red-500',
    textColor: 'text-white',
    logo: '/images/brands/CGV.png',
    logoAlt: 'CGV 로고',
  },
  {
    id: 'baskin',
    name: '베스킨라빈스',
    color: '#ED64A6',
    bgColor: 'bg-pink-500',
    textColor: 'text-white',
    logo: '/images/brands/베스킨라빈스.png',
    logoAlt: '베스킨라빈스 로고',
  },
  {
    id: 'paris',
    name: '파리바게뜨',
    color: '#1B3B6F',
    bgColor: 'bg-blue-900',
    textColor: 'text-white',
    logo: '/images/brands/파리바게뜨.png',
    logoAlt: '파리바게뜨 로고',
  },
  {
    id: 'gs25',
    name: 'GS25',
    color: '#3182CE',
    bgColor: 'bg-blue-500',
    textColor: 'text-white',
    logo: '/images/brands/GS25.png',
    logoAlt: 'GS25 로고',
  },
  {
    id: 'lotte',
    name: '롯데시네마',
    color: '#E53E3E',
    bgColor: 'bg-red-600',
    textColor: 'text-white',
    logo: '/images/brands/롯데시네마.png',
    logoAlt: '롯데시네마 로고',
  },
  {
    id: 'goobne',
    name: '굽네치킨',
    color: '#8B4513',
    bgColor: 'bg-amber-800',
    textColor: 'text-white',
    logo: '/images/brands/굽네치킨.png',
    logoAlt: '굽네치킨 로고',
  },
  {
    id: 'touslesjours',
    name: '뚜레쥬르',
    color: '#2E4B3C',
    bgColor: 'bg-green-900',
    textColor: 'text-white',
    logo: '/images/brands/뚜레쥬르.png',
    logoAlt: '뚜레쥬르 로고',
  },
  {
    id: 'wonderpark',
    name: '원더파크',
    color: '#BCAAA4',
    bgColor: 'bg-gray-300',
    textColor: 'text-black',
    logo: '/images/brands/원더파크.png',
    logoAlt: '원더파크 로고',
  },
];
