export { default as AdminPage } from './admin/AdminPage';
export { default as AuthSuccess } from './AuthSuccess';
export { default as BenefitPage } from './benefit/BenefitPage';
export { default as HomePage } from './HomePage';
export { default as MapPage } from './map/MapPage';
export { default as MymapPage } from './mymap/MymapPage';
export { default as MyPage } from './mypage/MyPage';
export { default as MyPageActivity } from './mypage/MyPageActivity';
export { default as ExtraInfo } from './user/extra-info/ExtraInfo';
